# Generated by Django 4.2.5 on 2023-09-05 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("aiot", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=40)),
            ],
        ),
        migrations.RenameField(
            model_name="control",
            old_name="room",
            new_name="room_id",
        ),
        migrations.RenameField(
            model_name="data",
            old_name="room",
            new_name="room_id",
        ),
        migrations.RenameField(
            model_name="floor",
            old_name="hotel",
            new_name="hotel_id",
        ),
        migrations.RenameField(
            model_name="floor",
            old_name="name",
            new_name="number",
        ),
        migrations.RenameField(
            model_name="room",
            old_name="hotel",
            new_name="floor_id",
        ),
        migrations.RemoveField(
            model_name="control",
            name="controlpoint",
        ),
        migrations.RemoveField(
            model_name="control",
            name="device_id",
        ),
        migrations.RemoveField(
            model_name="data",
            name="datapoint",
        ),
        migrations.RemoveField(
            model_name="data",
            name="device_id",
        ),
        migrations.AlterField(
            model_name="control",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="control",
            name="value",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="data",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="data",
            name="value",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="floor",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="hotel",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="hotel",
            name="name",
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name="room",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="room",
            name="number",
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name="DeviceParameter",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("param", models.CharField(max_length=40)),
                (
                    "device_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="aiot.device",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="control",
            name="device_parameter_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="aiot.deviceparameter",
            ),
        ),
        migrations.AddField(
            model_name="data",
            name="device_parameter_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="aiot.deviceparameter",
            ),
        ),
    ]
