# Generated by Django 4.2.5 on 2023-09-05 06:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aiot", "0002_device_rename_room_control_room_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="floor",
            name="number",
            field=models.CharField(max_length=20),
        ),
    ]
